sudo: required

language: generic

services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/kube-fi:latest .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

notifications:
  email: false