sudo: required

language: javascript

services:
  - docker

before_install:
  - docker build -t charlesarnaudo/kubefi

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master